[package]
name = "web_menorah"
version = "0.1.0"
authors = ["David Komer <david.komer@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3.4"
